from urllib.request import urlretrieve
from urllib.parse import quote
import os

datasets = {
    "ABC": {
        "prefix": "https://raw.githubusercontent.com/MarkGotham/When-in-Rome/master/Corpus/ABC/",
        "files": [
            "op127_mov1.txt",
            "op130_mov3.txt",
            "op131_mov3.txt",
            "op132_mov2.txt",
            "op135_mov3.txt",
            "op18_no2_mov1.txt",
            "op18_no3_mov3.txt",
            "op18_no5_mov1.txt",
            "op18_no6_mov3.txt",
            "op59_no2_mov1.txt",
            "op59_no3_mov3.txt",
            "op95_mov1.txt",
            "op127_mov2.txt",
            "op130_mov4.txt",
            "op131_mov4.txt",
            "op132_mov3.txt",
            "op135_mov4.txt",
            "op18_no2_mov2.txt",
            "op18_no3_mov4.txt",
            "op18_no5_mov2.txt",
            "op18_no6_mov4.txt",
            "op59_no2_mov2.txt",
            "op59_no3_mov4.txt",
            "op95_mov2.txt",
            "op127_mov3.txt",
            "op130_mov5.txt",
            "op131_mov5.txt",
            "op132_mov4.txt",
            "op18_no1_mov1.txt",
            "op18_no2_mov3.txt",
            "op18_no4_mov1.txt",
            "op18_no5_mov3.txt",
            "op59_no1_mov1.txt",
            "op59_no2_mov3.txt",
            "op74_mov1.txt",
            "op95_mov3.txt",
            "op127_mov4.txt",
            "op130_mov6.txt",
            "op131_mov6.txt",
            "op132_mov5.txt",
            "op18_no1_mov2.txt",
            "op18_no2_mov4.txt",
            "op18_no4_mov2.txt",
            "op18_no5_mov4.txt",
            "op59_no1_mov2.txt",
            "op59_no2_mov4.txt",
            "op74_mov2.txt",
            "op95_mov4.txt",
            "op130_mov1.txt",
            "op131_mov1.txt",
            "op131_mov7.txt",
            "op135_mov1.txt",
            "op18_no1_mov3.txt",
            "op18_no3_mov1.txt",
            "op18_no4_mov3.txt",
            "op18_no6_mov1.txt",
            "op59_no1_mov3.txt",
            "op59_no3_mov1.txt",
            "op74_mov3.txt",
            "op130_mov2.txt",
            "op131_mov2.txt",
            "op132_mov1.txt",
            "op135_mov2.txt",
            "op18_no1_mov4.txt",
            "op18_no3_mov2.txt",
            "op18_no4_mov4.txt",
            "op18_no6_mov2.txt",
            "op59_no1_mov4.txt",
            "op59_no3_mov2.txt",
            "op74_mov4.txt",
        ],
    },
    "m21BachChorales": {
        "prefix": "https://raw.githubusercontent.com/cuthbertLab/music21/master/music21/corpus/bach/choraleAnalyses/",
        "files": [
            "riemenschneider001.rntxt",
            "riemenschneider002.rntxt",
            "riemenschneider003.rntxt",
            "riemenschneider004.rntxt",
            "riemenschneider005.rntxt",
            "riemenschneider006.rntxt",
            "riemenschneider007.rntxt",
            "riemenschneider008.rntxt",
            "riemenschneider009.rntxt",
            "riemenschneider010.rntxt",
            "riemenschneider011.rntxt",
            "riemenschneider012.rntxt",
            "riemenschneider013.rntxt",
            "riemenschneider014.rntxt",
            "riemenschneider015.rntxt",
            "riemenschneider016.rntxt",
            "riemenschneider017.rntxt",
            "riemenschneider018.rntxt",
            "riemenschneider019.rntxt",
            "riemenschneider020.rntxt",
        ],
    },
    "m21Monteverdi": {
        "prefix": "https://raw.githubusercontent.com/cuthbertLab/music21/master/music21/corpus/monteverdi/",
        "files": [
            "madrigal.3.1.rntxt",
            "madrigal.3.10.rntxt",
            "madrigal.3.11.rntxt",
            "madrigal.3.12.rntxt",
            "madrigal.3.13.rntxt",
            "madrigal.3.14.rntxt",
            "madrigal.3.15.rntxt",
            "madrigal.3.16.rntxt",
            "madrigal.3.17.rntxt",
            "madrigal.3.18.rntxt",
            "madrigal.3.19.rntxt",
            "madrigal.3.2.rntxt",
            "madrigal.3.20.rntxt",
            "madrigal.3.3.rntxt",
            "madrigal.3.4.rntxt",
            "madrigal.3.5.rntxt",
            "madrigal.3.6.rntxt",
            "madrigal.3.7.rntxt",
            "madrigal.3.8.rntxt",
            "madrigal.3.9.rntxt",
            "madrigal.4.1.rntxt",
            "madrigal.4.10.rntxt",
            "madrigal.4.11.rntxt",
            "madrigal.4.12.rntxt",
            "madrigal.4.13.rntxt",
            "madrigal.4.14.rntxt",
            "madrigal.4.15.rntxt",
            "madrigal.4.16.rntxt",
            "madrigal.4.17.rntxt",
            "madrigal.4.18.rntxt",
            "madrigal.4.19.rntxt",
            "madrigal.4.2.rntxt",
            "madrigal.4.20.rntxt",
            "madrigal.4.3.rntxt",
            "madrigal.4.4.rntxt",
            "madrigal.4.5.rntxt",
            "madrigal.4.6.rntxt",
            "madrigal.4.7.rntxt",
            "madrigal.4.8.rntxt",
            "madrigal.4.9.rntxt",
            "madrigal.5.1.rntxt",
            "madrigal.5.2.rntxt",
            "madrigal.5.3.rntxt",
            "madrigal.5.4.rntxt",
            "madrigal.5.5.rntxt",
            "madrigal.5.6.rntxt",
            "madrigal.5.7.rntxt",
            "madrigal.5.8.rntxt",
        ],
    },
    "BachPreludes": {
        "prefix": "https://raw.githubusercontent.com/MarkGotham/When-in-Rome/master/Corpus/Bach_Preludes/",
        "files": [
            "19/human.txt",
            "15/human.txt",
            "14/human.txt",
            "18/human.txt",
            "12/human.txt",
            "23/human.txt",
            "1/human.txt",
            "16/human.txt",
            "24/human.txt",
            "17/human.txt",
            "13/human.txt",
            "7/human.txt",
            "4/human.txt",
            "20/human.txt",
            "6/human.txt",
            "10/human.txt",
            "9/human.txt",
            "11/human.txt",
            "8/human.txt",
            "22/human.txt",
            "21/human.txt",
            "5/human.txt",
            "2/human.txt",
            "3/human.txt",
        ],
    },
    "BeethovenSonatas": {
        "prefix": "https://raw.githubusercontent.com/MarkGotham/When-in-Rome/master/Corpus/BPS-FH/",
        "files": [
            "01-i.txt",
            "03-i.txt",
            "05-i.txt",
            "07-i.txt",
            "09-i.txt",
            "11-i.txt",
            "13-i.txt",
            "15-i.txt",
            "17-i.txt",
            "19-i.txt",
            "21-i.txt",
            "23-i.txt",
            "25-i.txt",
            "27-i.txt",
            "29-i.txt",
            "31-i.txt",
            "02-i.txt",
            "04-i.txt",
            "06-i.txt",
            "08-i.txt",
            "10-i.txt",
            "12-i.txt",
            "14-i.txt",
            "16-i.txt",
            "18-i.txt",
            "20-i.txt",
            "22-i.txt",
            "24-i.txt",
            "26-i.txt",
            "28-i.txt",
            "30-i.txt",
            "32-i.txt",
        ],
    },
    "Grounds": {
        "prefix": "https://raw.githubusercontent.com/MarkGotham/When-in-Rome/master/Corpus/Grounds/",
        "files": [
            "Purcell Sonata in G Minor Z807/human.txt",
            "Bach Crucifixus B Minor mass BWV232/human.txt",
            "Purcell Chacony_(Chaconne)/human.txt",
        ],
    },
    "HaydnOp20": {
        "prefix": "https://raw.githubusercontent.com/MarkGotham/When-in-Rome/master/Corpus/HaydnOp20/",
        "files": [
            "op20n1-01.txt",
            "op20n1-03.txt",
            "op20n2-01.txt",
            "op20n2-03.txt",
            "op20n3-01.txt",
            "op20n3-03.txt",
            "op20n4-01.txt",
            "op20n4-03.txt",
            "op20n5-01.txt",
            "op20n5-03.txt",
            "op20n6-01.txt",
            "op20n6-03.txt",
            "op20n1-02.txt",
            "op20n1-04.txt",
            "op20n2-02.txt",
            "op20n2-04.txt",
            "op20n3-02.txt",
            "op20n3-04.txt",
            "op20n4-02.txt",
            "op20n4-04.txt",
            "op20n5-02.txt",
            "op20n5-04.txt",
            "op20n6-02.txt",
            "op20n6-04.txt",
        ],
    },
    "Misc": {
        "prefix": "https://github.com/MarkGotham/When-in-Rome/blob/master/Corpus/Misc/",
        "files": ["Haydn Symphony 104 Movement 1/human.txt"],
    },
    "OpenScore": {
        "prefix": "https://raw.githubusercontent.com/MarkGotham/When-in-Rome/master/Corpus/OpenScore-LiederCorpus/",
        "files": [
            "Reichardt,_Louise/Zwölf_Deutsche_und_Italiänische_Romantische_Gesänge/10_Ida_(aus_Ariels_Offenbarungen)/analysis.txt",
            "Reichardt,_Louise/Zwölf_Gesänge,_Op.3/08_Kaeuzlein/analysis.txt",
            "Reichardt,_Louise/Zwölf_Gesänge,_Op.3/09_Hier_liegt_ein_Spielmann_begraben/analysis.txt",
            "Reichardt,_Louise/Zwölf_Gesänge,_Op.3/04_Wachtelwacht/analysis.txt",
            "Reichardt,_Louise/Zwölf_Gesänge,_Op.3/05_Betteley_der_Vögel/analysis.txt",
            "Reichardt,_Louise/Zwölf_Gesänge,_Op.3/02_Der_traurige_Wanderer/analysis.txt",
            "Reichardt,_Louise/Zwölf_Gesänge,_Op.3/03_Die_Blume_der_Blumen/analysis.txt",
            "Reichardt,_Louise/Zwölf_Gesänge,_Op.3/06_Kriegslied_des_Mays/analysis.txt",
            "Reichardt,_Louise/Zwölf_Gesänge,_Op.3/07_Die_Wiese/analysis.txt",
            "Reichardt,_Louise/Zwölf_Gesänge,_Op.3/01_Frühlingsblumen/analysis.txt",
            "Reichardt,_Louise/Sechs_Lieder_von_Novalis,_Op.4/5_Noch_ein_Bergmannslied/analysis.txt",
            "Schumann,_Robert/Frauenliebe_und_Leben,_Op.42/1_Seit_ich_ihn_gesehen/analysis.txt",
            "Schumann,_Robert/Frauenliebe_und_Leben,_Op.42/3_Ich_kann’s_nicht_fassen/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/03_Die_Rose,_die_Lilie/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/02_Aus_meinen_Tränen_sprießen/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/16_Die_alten,_bösen_Lieder/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/07_Ich_grolle_nicht/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/01_Im_wunderschönen_Monat_Mai/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/05_Ich_will_meine_Seele_tauchen/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/10_Hör’_ich_das_Liedchen_klingen/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/09_Das_ist_ein_Flöten_und_Geigen/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/14_Allnächtlich_im_Traume/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/04_Wenn_ich_in_deine_Augen_seh’/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/08_Und_wüssten’s_die_Blumen/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/11_Ein_Jüngling_liebt_ein_Mädchen/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/06_Im_Rhein,_im_heiligen_Strome/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/15_Aus_alten_Märchen_winkt_es/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/12_Am_leuchtenden_Sommermorgen/analysis.txt",
            "Schumann,_Robert/Dichterliebe,_Op.48/13_Ich_hab’_im_Traum_geweinet/analysis.txt",
            "Schubert,_Franz/Die_schöne_Müllerin,_D.795/12_Pause/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/19_Täuschung/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/13_Die_Post/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/05_Der_Lindenbaum/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/15_Die_Kraehe/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/08_Rückblick/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/23_Die_Nebensonnen/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/20_Der_Wegweiser/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/04_Erstarrung/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/18_Der_stuermische_Morgen/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/21_Das_Wirthshaus/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/01_Gute_Nacht/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/10_Rast_(Spätere_Fassung)/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/17_Im_Dorfe/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/11_Frühlingstraum/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/07_Auf_dem_Flusse/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/06_Wasserfluth/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/24_Der_Leiermann_(Spätere_Fassung)/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/22_Muth/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/09_Irrlicht/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/12_Einsamkeit_(Urspruengliche_Fassung)/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/03_Gefror’ne_Thränen/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/16_Letzte_Hoffnung/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/14_Der_greise_Kopf/analysis.txt",
            "Schubert,_Franz/Winterreise,_D.911/02_Die_Wetterfahne/analysis.txt",
            "Schubert,_Franz/Op.59/3_Du_bist_die_Ruh/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/01_Liebesbotschaft/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/04_Ständchen/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/09_Ihr_Bild/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/10_Das_Fischermädchen/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/13_Der_Doppelgänger/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/12_Am_Meer/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/14_Die_Taubenpost/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/05_Aufenthalt/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/06_In_der_Ferne/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/02_Kriegers_Ahnung/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/08_Der_Atlas/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/11_Die_Stadt/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/03_Frühlingssehnsucht/analysis.txt",
            "Schubert,_Franz/Schwanengesang,_D.957/07_Abschied/analysis.txt",
            "Coleridge-Taylor,_Samuel/_/Oh,_the_Summer/analysis.txt",
            "Chausson,_Ernest/7_Mélodies,_Op.2/7_Le_Colibri/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/6_Lieder,_Op.1/2_Wanderlied/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/6_Lieder,_Op.1/3_Warum_sind_denn_die_Rosen_so_blass/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/6_Lieder,_Op.1/1_Schwanenlied/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/6_Lieder,_Op.1/5_Morgenständchen/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/6_Lieder,_Op.1/6_Gondellied/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/6_Lieder,_Op.1/4_Mayenlied/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/3_Lieder/1_Sehnsucht/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/5_Lieder,_Op.10/4_Im_Herbste/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/5_Lieder,_Op.10/5_Bergeslust/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/5_Lieder,_Op.10/3_Abendbild/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/5_Lieder,_Op.10/1_Nach_Süden/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/5_Lieder,_Op.10/2_Vorwurf/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/6_Lieder,_Op.9/3_Der_Rosenkranz/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/6_Lieder,_Op.9/1_Die_Ersehnte/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/6_Lieder,_Op.9/4_Die_frühen_Gräber/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/6_Lieder,_Op.9/6_Die_Mainacht/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/6_Lieder,_Op.9/5_Der_Maiabend/analysis.txt",
            "Hensel,_Fanny_(Mendelssohn)/6_Lieder,_Op.9/2_Ferne/analysis.txt",
            "Franz,_Robert/6_Gesänge,_Op.14/5_Liebesfrühling/analysis.txt",
            "Brahms,_Johannes/7_Lieder,_Op.48/3_Liebesklage_des_Mädchens/analysis.txt",
            "Brahms,_Johannes/6_Songs,_Op.3/3_Liebe_und_Frühling_II/analysis.txt",
            "Chaminade,_Cécile/_/Amoroso/analysis.txt",
            "Holmès,_Augusta_Mary_Anne/Les_Heures/4_L’Heure_d’Azur/analysis.txt",
            "Mahler,_Gustav/Kindertotenlieder/4_Oft_denk’_ich,_sie_sind_nur_ausgegangen/analysis.txt",
            "Mahler,_Gustav/Kindertotenlieder/2_Nun_seh’_ich_wohl,_warum_so_dunkle_Flammen/analysis.txt",
            "Lang,_Josephine/6_Lieder,_Op.25/4_Lied_(Immer_sich_rein_kindlich_erfreu’n)/analysis.txt",
            "Jaëll,_Marie/4_Mélodies/1_À_toi/analysis.txt",
            "Wolf,_Hugo/Eichendorff-Lieder/13_Der_Scholar/analysis.txt",
            "Wolf,_Hugo/Eichendorff-Lieder/19_Die_Nacht/analysis.txt",
            "Wolf,_Hugo/Eichendorff-Lieder/20_Waldmädchen/analysis.txt",
            "Wolf,_Hugo/Eichendorff-Lieder/15_Unfall/analysis.txt",
            "Wolf,_Hugo/Eichendorff-Lieder/04_Das_Ständchen/analysis.txt",
            "Wolf,_Hugo/Eichendorff-Lieder/08_Nachtzauber/analysis.txt",
            "Wolf,_Hugo/Eichendorff-Lieder/14_Der_verzweifelte_Liebhaber/analysis.txt",
            "Schumann,_Clara/_/Die_gute_Nacht/analysis.txt",
            "Schumann,_Clara/6_Lieder,_Op.13/2_Sie_liebten_sich_beide/analysis.txt",
            "Schumann,_Clara/6_Lieder,_Op.13/3_Liebeszauber/analysis.txt",
            "Schumann,_Clara/6_Lieder,_Op.13/1_Ich_stand_in_dunklen_Träumen/analysis.txt",
            "Schumann,_Clara/6_Lieder,_Op.13/6_Die_stille_Lotosblume/analysis.txt",
            "Schumann,_Clara/6_Lieder,_Op.23/4_Auf_einem_grünen_Hügel/analysis.txt",
            "Schumann,_Clara/Lieder,_Op.12/04_Liebst_du_um_Schönheit/analysis.txt",
        ],
    },
    "TAVERN": {
        "prefix": "https://raw.githubusercontent.com/MarkGotham/When-in-Rome/master/Corpus/TAVERN/",
        "files": [
            "Beethoven/B063_A.txt",
            "Beethoven/B064_A.txt",
            "Beethoven/B065_A.txt",
            "Beethoven/B066_A.txt",
            "Beethoven/B068_A.txt",
            "Beethoven/B069_A.txt",
            "Beethoven/B070_A.txt",
            "Beethoven/B071_a.txt",
            "Beethoven/B072_A.txt",
            "Beethoven/B073_A.txt",
            "Beethoven/B075_A.txt",
            "Beethoven/B076_A.txt",
            "Beethoven/B077_A.txt",
            "Beethoven/B078_A.txt",
            "Beethoven/B080_A.txt",
            "Beethoven/Opus34_A.txt",
            "Beethoven/Opus76_A.txt",
            "Beethoven/B063_B.txt",
            "Beethoven/B064_B.txt",
            "Beethoven/B065_B.txt",
            "Beethoven/B066_B.txt",
            "Beethoven/B068_B.txt",
            "Beethoven/B069_B.txt",
            "Beethoven/B070_B.txt",
            "Beethoven/B071_B.txt",
            "Beethoven/B072_B.txt",
            "Beethoven/B073_B.txt",
            "Beethoven/B075_B.txt",
            "Beethoven/B076_B.txt",
            "Beethoven/B077_B.txt",
            "Beethoven/B078_B.txt",
            "Beethoven/B080_B.txt",
            "Beethoven/Opus34_B.txt",
            "Beethoven/Opus76_B.txt",
            "Mozart/K179_B.txt",
            "Mozart/K501_A.txt",
            "Mozart/K613_A.txt",
            "Mozart/K573_B.txt",
            "Mozart/K613_B.txt",
            "Mozart/K501_B.txt",
            "Mozart/K398_A.txt",
            "Mozart/K025_B.txt",
            "Mozart/K398_B.txt",
            "Mozart/K265_A.txt",
            "Mozart/K353_A.txt",
            "Mozart/K354_B.txt",
            "Mozart/K353_B.txt",
            "Mozart/K354_A.txt",
            "Mozart/K265_B.txt",
            "Mozart/K455_A.txt",
            "Mozart/K455_B.txt",
            "Mozart/K179_A.txt",
            "Mozart/K573_A.txt",
            "Mozart/K025_A.txt",
        ],
    },
}

datasetFolder = "dataset"

for datasetName, dataset in datasets.items():
    print(datasetName)
    prefix = dataset["prefix"]
    files = dataset["files"]
    for f in files:
        url = os.path.join(prefix, quote(f))
        localName = f.replace("/", "_")
        info = urlretrieve(url, f"{datasetFolder}/{datasetName}_{localName}")
        print(info[0])
